name: eauxiliary
description: "一个E听说的答案工具"
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  file_picker: ^10.3.1
  provider: ^6.1.1
  url_launcher: ^6.2.5
  package_info_plus: ^8.3.0
  filesystem_picker: ^4.1.0
  share_plus: ^10.1.4
  shizuku_api: ^1.2.1
  http: ^1.2.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  html: ^0.15.4
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  web_socket_channel: ^3.0.2
  uuid: ^4.3.3
  archive: ^4.0.5
  path: ^1.9.1
  screenshot: ^3.0.0
  image: ^4.5.4
  gal: ^2.3.1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/app_icon.png

  # 添加HarmonyOS Sans字体配置
  fonts:
    - family: HarmonyOS_SansSC
      fonts:
        - asset: assets/fonts/HarmonyOS_SansSC_Black.ttf
          weight: 900
        - asset: assets/fonts/HarmonyOS_SansSC_Bold.ttf
          weight: 700
        - asset: assets/fonts/HarmonyOS_SansSC_Medium.ttf
          weight: 500
        - asset: assets/fonts/HarmonyOS_SansSC_Regular.ttf
          weight: 400
        - asset: assets/fonts/HarmonyOS_SansSC_Light.ttf
          weight: 300
        - asset: assets/fonts/HarmonyOS_SansSC_Thin.ttf
          weight: 100
